### ISSUE TITLE
Heart Count Resets after 999 Hearts

### ISSUE THREAD

**Issue by ryandonsullivan** [wpsitecare/heart-this#11]
Related to this forum post: https://wordpress.org/support/topic/heart-count-resets-after-999/

I'm pretty sure it's resetting because of [this value](https://github.com/wpsitecare/heart-this/blob/017b2f32182270c444e8677945dbb08a44c63b7b/js/src/heartThis.js#L16), but I'm not sure what impact there will be if that value is changed to something like 10000.

**Comment by ozzyrod** [comment]
https://github.com/cipherdevgroup/heart-this/commit/8b10f871304d0d79fedf2b1d63f06cdfc84533d7 completes the fix of this issue
